site_name: My Docs
nav:
    - Home: index.md
    - Python: python/virtual-environment.md
    - Docker: 
        - Installation: docker/docker-installation.md
    - VSCode:
        - Configuration: vscode/configuration.md
    
theme: readthedocs
